[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/__/auth/handler"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
